### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mathiser** [Project-MONAI/monai-deploy-app-sdk#251]
**Describe the bug**
Operators work when executed alone, but fails with `monai.deploy.exceptions.ItemNotExistsError: '/operators/d3de6feb-9315-4f65-8536-8d6b6e716636/0/output/' does not exist.` when run consecutively. Checking .monai_workdir reveils that the folder _does_ in fact exits.

**Steps/Code to reproduce bug**
Consider the following minimal app:
```
@md.input("", DataPath, IOType.DISK)
@md.output("", DataPath, IOType.DISK)
class CopyOP(Operator):
    def __init__(self):
        super().__init__()

    def compute(self, op_input: InputContext, op_output: OutputContext, context: ExecutionContext):
        in_path = op_input.get().path
        out_path = op_output.get().path
        for f in os.listdir(in_path):
            shutil.copy2(os.path.join(in_path, f), out_path)

class App(Application):
    def compose(self):
        logging.info("started")
        copy1 = CopyOP()
        copy2 = CopyOP()

        self.add_flow(copy1, copy2)

if __name__ == "__main__":
    App(do_run=True)
```

If I try to run a single CopyOP() with self.add_operator(copy1), it works. Adding them consecutively yields the following exception:
```
Traceback (most recent call last):
  File "/home/mathis/projects/docker_images/inference_server/model_repository/models/simplemonai/app.py", line 29, in <module>
    App(do_run=True)
  File "/home/mathis/anaconda3/envs/pydicom/lib/python3.9/site-packages/monai/deploy/core/application.py", line 129, in __init__
    self.run(log_level=args.log_level)
  File "/home/mathis/anaconda3/envs/pydicom/lib/python3.9/site-packages/monai/deploy/core/application.py", line 429, in run
    executor_obj.run()
  File "/home/mathis/anaconda3/envs/pydicom/lib/python3.9/site-packages/monai/deploy/core/executors/single_process_executor.py", line 125, in run
    op.compute(op_exec_context.input_context, op_exec_context.output_context, op_exec_context)
  File "/home/mathis/projects/docker_images/inference_server/model_repository/models/simplemonai/app.py", line 16, in compute
    out_path = op_output.get().path
  File "/home/mathis/anaconda3/envs/pydicom/lib/python3.9/site-packages/monai/deploy/core/io_context.py", line 85, in get
    raise ItemNotExistsError(f"'{key}' does not exist.")
monai.deploy.exceptions.ItemNotExistsError: '/operators/d3de6feb-9315-4f65-8536-8d6b6e716636/0/output/' does not exist.
```
**Expected behavior**
Expected operators to run consecutively

**Environment details (please complete the following information)**

- OS/Platform: Ubuntu 20.04
- Python Version: 3.9.7
- Method of MONAI Deploy App SDK install: pip in a conda env
- SDK Version: 0.2.1

Thanks in advance

**Comment by MMelQin** [comment]
@mathiser Thank you for reporting this issue, which is reproducible. This behavior, or limitation, is by design, and I'd explain below.

Only the last operator's op_output can be a DISK type, and mapped to the application's output. I actually at times had the needs to output files from an "inside operator",  and after discussion with @gigony , we decided on this keep this limitation for the following reasons:
- to the consumers of the application, there should be on input (dir) and one output (dir)
- for performance reasons, it is best to have memory objects passed between operators
- for non-leaf operators, the context: ExecutionContext argument has the property `output`, which is the application's output (dir), and any operator can get the path of it, and write folder/files to it
- if there is a need to save files as the output of a non-leaf operator and pass the files as input to another operator, the non-leaf operator can save the files in the application's output folder, then wrap the path in (str) object as output with IOType_IN_MEMORY, and then link the output as input to the next operator as IOType.IN_MEMORY. This makes the edge/linkage both dynamic and deterministic
- For applications with multiple leaf operators, then each leaf operator's op_output can be mapped to the application's output (dir). I am actually extending the ai_spleen_seg_app to have two leaf operators, one being the DICOM Seg writer, the other a 3D  surface mesh writer, snippet below.

Hope you see these as good reasons, too, to have this known limitation.

```
    def compose(self):
        """Creates the app specific operators and chain them up in the processing DAG."""

        self._logger.debug(f"Begin {self.compose.__name__}")

        # Creates the custom operator(s) as well as SDK built-in operator(s).
        study_loader_op = DICOMDataLoaderOperator()
        series_selector_op = DICOMSeriesSelectorOperator(Sample_Rules_Text)
        series_to_vol_op = DICOMSeriesToVolumeOperator()
        # Model specific inference operator, supporting MONAI transforms.
        spleen_seg_op = SpleenSegOperator()
        # Creates DICOM Seg writer with segment label name in a string list
        dicom_seg_writer = DICOMSegmentationWriterOperator(seg_labels=["Spleen"])

        mesh_conversion_op = MeshConvertionOperator(output_file="test.stl")

        # Create the processing pipeline, by specifying the upstream and downstream operators, and
        # ensuring the output from the former matches the input of the latter, in both name and type.
        self.add_flow(study_loader_op, series_selector_op, {"dicom_study_list": "dicom_study_list"})
        self.add_flow(
            series_selector_op, series_to_vol_op, {"study_selected_series_list": "study_selected_series_list"}
        )
        self.add_flow(series_to_vol_op, spleen_seg_op, {"image": "image"})
        # Note below the dicom_seg_writer requires two inputs, each coming from a upstream operator.
        self.add_flow(
            series_selector_op, dicom_seg_writer, {"study_selected_series_list": "study_selected_series_list"}
        )
        self.add_flow(spleen_seg_op, dicom_seg_writer, {"seg_image": "seg_image"})

        self.add_flow(spleen_seg_op, mesh_conversion_op, {"seg_image": "image"})

        self._logger.debug(f"End {self.compose.__name__}")
```

**Comment by mathiser** [comment]
@MMelQin, Thank you for elaborating this for me. It drove me insane yesterday, as I could not find any documentation about the situation. 

I think the reasons you state are very sensible - the only thing that bothers be is that it (at least to me) makes debugging/developing of long and complex workflows more painful, as visual inspection of intermittent steps will be somewhat more cumbersome. 

Thanks again - I think we can close this then.

**Comment by MMelQin** [comment]
Thanks again. I've created a new issue for improving the doc.
