### ISSUE TITLE
ClaraVizOperator import Fails

### ISSUE THREAD

**Issue by vikashg** [Project-MONAI/monai-deploy-app-sdk#275]
Hello everyone, 
After getting the latest main branch and upgrading monai deploy. Running the 03_segmentation_viz_app gives the following error
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_510135/3062323273.py in <module>
     27 from monai.deploy.operators.dicom_series_selector_operator import DICOMSeriesSelectorOperator
     28 from monai.deploy.operators.dicom_series_to_volume_operator import DICOMSeriesToVolumeOperator
---> 29 from monai.deploy.operators.clara_viz_operator import ClaraVizOperator

ModuleNotFoundError: No module named 'monai.deploy.operators.clara_viz_operator'
```
I checked that in my folder operators there is the file clara_viz_operator.py. In addition I checked __init__.py and there exist the required line 

```
 29 from .clara_viz_operator import ClaraVizOperator
```
I donot understand what is going on? Any comments @AndreasHeumann

**Comment by AndreasHeumann** [comment]
@vikashg Sorry for the late answer, I did not get an e-mail notification about beeing assigned to this issue.

I can reproduce that locally, this happens if you uninstall clara-viz with pip.

The notebook is using this
`!python -c "import clara.viz" || pip install --upgrade -q "clara-viz"`
to check if Clara Viz is installed and install it if not.

The problem is if you have Clara Viz once installed and uninstall it again the `site-packages/clara/viz/` directory is not removed by pip althoug it is empty.

And since Python 3.3 import from an empty directory is not returning an error
http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-missing-init-py-trap

So the line above is not installing Clara Viz although it's not installed.

The only way I can think of to fix this is to change the noteboot to install clara-viz-widgets instead.

`!python -c "import clara.viz.widgets" || pip install --upgrade -q "clara-viz-widgets"`

Let me know if this is fixing your problem.

**Comment by vikashg** [comment]
Thanks @AndreasHeumann I will be working on it. 
Vikash

**Comment by MMelQin** [comment]
@vikashg can you confirm and close this as fixed?

**Comment by vikashg** [comment]
Let me try this again. 
Thanks

**Comment by vikashg** [comment]
I just tested and this issue is resolved on my end.

**Comment by MMelQin** [comment]
> I just tested and this issue is resolved on my end.

Thank you for retesting and closing the bug!
