### ISSUE TITLE
[BUG] DICOM SR Writer

### ISSUE THREAD

**Issue by vikashg** [Project-MONAI/monai-deploy-app-sdk#341]
**Describe the bug**
If `copy_tags` is set to `True`, I get the following error. However when it is set to false the code executes normally 

```
Executing operator DICOMTextSRWriterOperator (Process ID: 1003670, Operator ID: f0d114cf-2baf-4ad4-8c77-883a50a6ca4f)
Traceback (most recent call last):
  File "breast_classification_application_2.py", line 165, in <module>
    main()
  File "breast_classification_application_2.py", line 162, in main
    app.run(input=image_dir, output='./output', model=model_path)
  File "/home/gupta/anaconda3/envs/monai-1.0/lib/python3.8/site-packages/monai/deploy/core/application.py", line 429, in run
    executor_obj.run()
  File "/home/gupta/anaconda3/envs/monai-1.0/lib/python3.8/site-packages/monai/deploy/core/executors/single_process_executor.py", line 125, in run
    op.compute(op_exec_context.input_context, op_exec_context.output_context, op_exec_context)
  File "/home/gupta/anaconda3/envs/monai-1.0/lib/python3.8/site-packages/monai/deploy/operators/dicom_text_sr_writer_operator.py", line 178, in compute
    raise ValueError("Missing input, list of 'StudySelectedSeries'.")
ValueError: Missing input, list of 'StudySelectedSeries'.
```
[breast_classification_application_2.txt](https://github.com/Project-MONAI/monai-deploy-app-sdk/files/9542039/breast_classification_application_2.txt)

**Steps/Code to reproduce bug**
I have attached the code here.

**Comment by MMelQin** [comment]
Thanks for the issue @vikashg. The issue is not a bug in the SR Writer, as it legitimately raise the error for missing the selected original DICOM instance which it is being forced to copy tags from.

There is a simple error in the attached application code, in that the `sr_writer_op` also needs two(2) inputs, one from Classifier operator, and the other, missing one, from the series_selector_op which is required when the `copy_tags` is true. So, please add the following input, 
    `self.add_flow( series_selector_op, sr_writer_op, {"study_selected_series_list": "study_selected_series_list"})`

**Comment by vikashg** [comment]
Thanks @MMelQin I guess trying to debug at 5 in the morning is never a good idea :) It works now... Thanks so much.

**Comment by MMelQin** [comment]
Thanks @vikashg I noticed the new issue 2AM my time!
